title: CSC Cloud — Using CSC Cloud

baseurl: /csc-cloud
repository: lvarin/csc-cloud

plugins:
  - jekyll-sitemap
  - raw_content

collections:
    lectures:
        output: true
    lectures-containers:
        output: true
    exercises:
        output: true
    exercises-containers:
        output: true
    extras:
        output: true

defaults:
  -
    scope:
      path: "_lectures"
    values:
      layout: "slides-csc"
  -
    scope:
      path: "_lectures-comntainers"
    values:
      layout: "slides-csc"
  -
    scope:
      path: "_exercises"
    values:
      layout: "default"
  -
    scope:
      path: "_exercises-containers"
    values:
      layout: "default"
  -
    scope:
      path: "_extras"
    values:
      layout: "default"
